site_name: Documentation
site_url: https://sitename.example
# Repository
#repo_url: https://calendar.google.com
#repo_name: Google Calendar # <- This is the visible text
watch:
  - includes
theme:
  name: material
  features:
    #    - navigation.tabs # THIS enables the top nav bar (as tabs)
    - content.tooltips
    - content.code.copy
    - content.code.annotate
    - search.highlight
    - navigation.top
  #    - navigation.sections
  #    - toc.integrate
  #    - navigation.footer
  #    - navigation.instant
  #    - navigation.tracking
  #    - navigation.indexes
  #    - navigation.expand
  font:
#      text: Inter
#      text: Montserrat
#      text: Lato
#      text: ubuntu
  palette:
    - primary: white
    # Light Mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Light mode
    #        primary: white
    #      accent: deep orange
    #      accent: blue
    #    code: Red Hat Mono
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
  #      primary: black
  #      accent: deep purple

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#  - https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/main.min.js
#  - js/calendar-setup.js
#extra_css:
#  - https://cdn.jsdelivr.net/npm/fullcalendar@6.1.8/main.min.css

plugins:
  - search
#  - blog
#  - meta
#  - blogging
#  - glightbox:
#      touchNavigation: true
#      loop: false
#      effect: zoom
#      slide_effect: slide
#      width: 100%
#      height: auto
#      zoomable: true
#      draggable: true
#      skip_classes:
#        - custom-skip-class-name
#      auto_themed: false
#      auto_caption: false
#      caption_position: bottom
#      background: white
#      shadow: true
#      manual: false
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-repo
    #      name: GitHub
    - icon: fontawesome/brands/web-awesome
      link: https://www.tui.co.uk/
#      name: TUI
#nav:
#  - Home: index.md
#  - Mercedes-Benz:
#      - Mercedes-Benz C-Class: mercedes-benz/comparison-of-class.md
#      - The most popular: mercedes-benz/most-popular.md
#      - The braking energy: mercedes-benz/braking-energy.md
#      - Environmental Impact: mercedes-benz/environmental-impact.md
#      - C-Class models: https://www.mercedes-benz.co.uk/passengercars/models/saloon/c-class/overview.html
#      - Suspension arm: mercedes-benz/suspension-arm.md
#  - About: about.md
#  - Blog: blog.md
#  - GitHub: https://github.com
#  - Community:
#    - Contributing:
#      - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
